#!/usr/bin/env bash
# install nginx
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > index.html
sudo mv index.html /var/www/html

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
